### ISSUE TITLE
Is it possible to get translations from CMS?

### ISSUE THREAD

**Issue by dave-calleja-markor** [Alexandre-Fernandez/astro-i18n#14]
I would like to get translations etc from a CMS. Is that possible or does everything need to be present at build time?

thanks!

**Comment by Alexandre-Fernandez** [comment]
At the moment it's not possible, however I can add this feature, what format do you receive your translations in ? Can you give me an example ?

**Comment by dave-calleja-markor** [comment]
Thanks for swift reply! I can format it exactly as expected in config / json files in documentation 🙂

**Comment by Alexandre-Fernandez** [comment]
Actually this is already possible, you can add your translations in the `astroI18n.translations` object. 
There's just no easy helper to merge your fetched translations to the astro ones. 
I'll think about the best way to implement this and add it in the next version.
I'm closing this since the feature already exists.

**Comment by dave-calleja-markor** [comment]
Thanks!

**Comment by Alexandre-Fernandez** [comment]
added in `1.6.0`, see `astroI18n.addTranslations`
